/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmRemoveDialog: typeof import('./src/components/ConfirmRemoveDialog.vue')['default']
    EvolutionChain: typeof import('./src/components/EvolutionChain.vue')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    NotificationDialog: typeof import('./src/components/NotificationDialog.vue')['default']
    PaginationComponent: typeof import('./src/components/PaginationComponent.vue')['default']
    PokemonCard: typeof import('./src/components/PokemonCard.vue')['default']
    PokemonCounter: typeof import('./src/components/PokemonCounter.vue')['default']
    PokemonDetailsDialog: typeof import('./src/components/PokemonDetailsDialog.vue')['default']
    PokemonList: typeof import('./src/components/PokemonList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
